from __future__ import annotations

import gc
from dataclasses import dataclass

import numpy as np
import pandas as pd

from .config import resolve_path
from .legacy import activate
from .runtime import log, stage

AUX_NAMES = ("reverse", "middle", "ball", "strike")


@dataclass
class PreparedData:
    frame: pd.DataFrame
    train_mask: np.ndarray
    valid_mask: np.ndarray
    y_valid: np.ndarray
    gt_valid: np.ndarray
    aux: pd.DataFrame
    feature_sets: dict[str, list[str]]
    categorical_extra: set[str]


def _legacy_config(cfg: dict) -> dict:
    """Minimal config contract expected by the recovered historical helpers."""
    return {
        "paths": {
            "processed_file": str(resolve_path(cfg, cfg["data"]["processed_train"])),
            "output_dir": str(resolve_path(cfg, cfg["output"]["dir"])),
        },
        "data": {
            "target_col": cfg["data"]["target_col"],
            "season_col": cfg["data"]["season_col"],
            "row_id_col": "row_id",
            "train_seasons": [2019, 2020, 2021, 2022],
            "val_seasons": [2023],
            "test_seasons": [2024],
        },
        "raw_catboost": {
            "iterations": 3000,
            "learning_rate": 0.03,
            "depth": 6,
            "l2_leaf_reg": 10.0,
            "random_strength": 1.0,
            "early_stopping_rounds": 100,
            "task_type": "GPU",
            "devices": "0",
            "verbose": 50,
            "threshold": 0.5,
        },
    }


def auxiliary_targets(frame: pd.DataFrame) -> pd.DataFrame:
    """Use the exact auxiliary reconstruction from the SAFE source snapshot."""
    activate()
    import run_multitask_outcome_boosting as multi_core

    return multi_core.auxiliary_targets(frame)


def prepare(cfg: dict) -> PreparedData:
    """Recreate the historical feature state used by the SAFE constituent models.

    The important rule here is provenance, not cleanup: every history/profile helper,
    categorical declaration, and feature ordering comes from the Git object snapshot
    that contains the 981.489 SAFE artifact.  Do not replace these calls with a
    "simplified equivalent" unless prediction-level equivalence is proven first.
    """
    activate()
    import build_recent_regime_submissions as recent_core
    import run_context_interaction_screen as context_core
    import run_frozen_domain_path_probe as path_core
    import run_frozen_season_anchor_probe as anchor_core
    import run_multitask_outcome_boosting as multi_core
    import run_offset_residual_boosting as offset_core
    import run_regime_feature_prediction_suite as regime_core

    target = cfg["data"]["target_col"]
    season_col = cfg["data"]["season_col"]
    valid_season = int(cfg["data"]["validation_season"])

    with stage("load + canonical row features"):
        frame, _ = recent_core.prepare_frame(_legacy_config(cfg))
        frame = frame.reset_index(drop=True)
        frame[season_col] = pd.to_numeric(frame[season_col], errors="raise").astype(int)
        frame["game_type"] = frame["game_type"].astype("string").str.strip().str.upper()

    # Several frozen profile builders in the recovered scripts were intentionally
    # called before the 2024 split.  Their per-row values remain season-frozen: a row
    # from season s only reads states accumulated from seasons < s.
    with stage("full-frame auxiliary reconstruction"):
        aux_full = multi_core.auxiliary_targets(frame)

    with stage("frozen historical features"):
        anchor_core.add_frozen_anchor_features(
            frame,
            season_col=season_col,
            pitcher_col="pitcher_id",
            n_col="asof_pitcher_n",
            count_tolerance=0.05,
        )
        banchor = offset_core.add_batter_anchor(frame)
        anchor_cross = offset_core.add_anchor_cross(frame)
        matchup = offset_core.add_frozen_matchup(frame)
        count_profile = offset_core.add_frozen_count_profiles(frame)
        pressure_profile = offset_core.add_frozen_pressure_profiles(frame)
        domain_profile = offset_core.add_frozen_domain_profiles(frame)
        aux_profile = offset_core.add_frozen_aux_profiles(frame, aux_full, "pressure")
        conditional_profile = offset_core.add_frozen_conditional_profiles(frame, aux_full, False)

        context_core.add_context_interactions(frame)
        paths = (
            path_core.add_paths(frame, "pitcher_id", season_col, target)
            + path_core.add_paths(frame, "batter_id", season_col, target)
        )
        # This filter is literal historical behavior.  Target-rate path outputs were
        # generated by the helper but excluded from every SAFE constituent feature set.
        paths = [x for x in paths if not x.endswith("_rate")]
        path_cats = {x for x in paths if x.endswith(("last_gt", "current_x_last"))}
        regime_core.EXTRA_CATEGORICAL.update(path_cats)

    train_mask0 = frame[season_col].lt(valid_season).to_numpy()
    valid_mask0 = frame[season_col].eq(valid_season).to_numpy()
    if not train_mask0.any() or not valid_mask0.any():
        raise RuntimeError("recovered SAFE split is empty")

    # The exact snapshot registers context interaction columns as categorical inside
    # run_regime_feature_prediction_suite.EXTRA_CATEGORICAL.  This is a critical
    # difference from the first Bitaboost rewrite, where they were accidentally
    # coerced to numeric NaNs.
    with stage("regime features"):
        train = frame.loc[train_mask0].copy()
        valid = frame.loc[valid_mask0].copy()
        regime_core.add_regime_features(train, valid, season_col=season_col, recent_start=2023)
        frame = pd.concat([train, valid], axis=0).sort_index(kind="stable")
        del train, valid

    # One consolidation after all historical feature writes reduces pandas block
    # fragmentation without changing feature values, dtypes, or ordering.
    frame = frame.copy()
    train_mask = frame[season_col].lt(valid_season).to_numpy()
    valid_mask = frame[season_col].eq(valid_season).to_numpy()

    base = [
        *recent_core.feature_set("recent_raw_game_type"),
        regime_core.RECENT_FLAG,
        *regime_core.FAST_CONT,
        *regime_core.RANGE_CONT,
        *context_core.INTERACTION_COLUMNS,
        *paths,
    ]
    anchor_success = [
        "eng_anchor_available",
        "eng_anchor_gap_n",
        "eng_anchor_success_rate",
        "eng_since_anchor_success_rate",
        "eng_since_anchor_success_minus_long",
    ]
    multi_anchor = [
        x
        for short in ("reverse", "middle", "ball", "strike")
        for x in (
            f"eng_anchor_{short}_rate",
            f"eng_since_anchor_{short}_rate",
            f"eng_since_anchor_{short}_minus_long",
        )
    ]

    # DIRECT / JOINT / standalone reverse-middle heads: exact rich recipe.
    rich = [
        *base,
        *anchor_success,
        *multi_anchor,
        *banchor,
        *anchor_cross,
        *matchup,
        *count_profile,
        *pressure_profile,
        *domain_profile,
        *aux_profile,
    ]

    # Hurdle lineage used --anchor but not --multi-anchor, then added conditional
    # profiles on top of the same frozen context family.
    hurdle = [
        *base,
        *anchor_success,
        *banchor,
        *anchor_cross,
        *matchup,
        *count_profile,
        *pressure_profile,
        *domain_profile,
        *aux_profile,
        *conditional_profile,
    ]

    # The promoted cross1 residual predates expansion of add_anchor_cross.  Its
    # preserved columns are the original first five cross outputs, in original order.
    old_cross1 = [
        "eng_anchor_cross_success",
        "eng_anchor_cross_middle",
        "eng_anchor_pitch_success_shrunk",
        "eng_anchor_batter_success_shrunk",
        "eng_anchor_gap_logratio",
    ]
    offset = [*base, *anchor_success, *banchor, *old_cross1]

    # Final 4.15% F correction came from the pre-rich --ids structured runner.
    structured = [
        *recent_core.feature_set("recent_raw_game_type"),
        "pitcher_id",
        "batter_id",
        regime_core.RECENT_FLAG,
        *regime_core.FAST_CONT,
        *regime_core.RANGE_CONT,
        *context_core.INTERACTION_COLUMNS,
        *paths,
    ]
    regime_core.EXTRA_CATEGORICAL.update({"pitcher_id", "batter_id"})

    feature_sets = {
        "rich": rich,
        "hurdle": hurdle,
        "offset": offset,
        "structured": structured,
    }
    for name, features in feature_sets.items():
        if len(features) != len(set(features)):
            dup = sorted({x for x in features if features.count(x) > 1})
            raise RuntimeError(f"duplicate {name} features: {dup}")
        missing = sorted(set(features) - set(frame.columns))
        if missing:
            raise RuntimeError(f"missing {name} features: {missing}")

    y = pd.to_numeric(frame.loc[valid_mask, target], errors="raise").to_numpy(np.float64)
    gt = frame.loc[valid_mask, "game_type"].astype(str).to_numpy()
    log(
        f"[data] train={int(train_mask.sum()):,} valid={int(valid_mask.sum()):,} "
        f"rich={len(rich)} hurdle={len(hurdle)} offset={len(offset)} structured={len(structured)}"
    )
    gc.collect()
    return PreparedData(
        frame=frame,
        train_mask=train_mask,
        valid_mask=valid_mask,
        y_valid=y,
        gt_valid=gt,
        aux=aux_full,
        feature_sets=feature_sets,
        categorical_extra=path_cats | {"pitcher_id", "batter_id"} | set(context_core.INTERACTION_COLUMNS),
    )
